Test/cities
fga-eps-mds/2022-2-schedula-front pull request #19
Opened 2023-01-25 21:50 UTC by kleidson-alves

2023-01-26 12:47 UTC, twistershark requested changes

2023-01-27 00:14 UTC, lucas229 commented on src/components/page-header/page-header.spec.tsx
> +      <PageHeader title="Título" subtitle="Subtítulo" children="Children" />
Corrigido.

2023-01-27 00:17 UTC, lucas229 commented on src/features/users/components/user-form/user-form.spec.tsx
> +  /* it('should be able to create a city', async () => {
Deletei o arquivo.
Esses testes não deveriam ter sido adicionados ainda.

2023-01-27 22:08 UTC, twistershark approved these changes

2023-01-28 14:34 UTC, merged